sudo: false
language: node_js
node_js:
  - "v12.16.2"
cache:
  directories:
    - "$HOME/.npm"
branches:
  only:
    - develop
install:
  - npm ci
  # keep the npm cache around to speed up installs
script:
  - npm run coveralls
